# docker-composeのファイル形式のバージョン
version: '3.8'

# 起動するコンテナ（サービス）の一覧を定義します
services:
  # 'api'という名前のサービスを定義します（この名前は自由に変更できます）
  api:
    # イメージのビルド方法に関する設定
    build:
      # Dockerfileが存在するディレクトリ（カレントディレクトリを指す「.」）
      context: .
      # 使用するDockerfileの名前
      dockerfile: Dockerfile
    # ポートのマッピング設定 ( [ホストPCのポート]:[コンテナのポート] )
    # DockerfileのCMDで「--port 80」と指定されているため、コンテナ側のポートは80です。
    # これにより、ホストPCの8000番ポートへのアクセスが、コンテナの80番ポートに転送されます。
    # 結果として、ブラウザやcurlから http://localhost:8000 でアクセス可能になります。
    ports:
      - "8000:80"
    # ボリュームのマッピング設定 ( [ホストPCのディレクトリ]:[コンテナのディレクトリ] )
    # ホストPCのソースコードの変更を、コンテナを再起動せずに即時反映させるための設定です。
    # Dockerfileの「COPY ./app ./app」と対応させています。
    volumes:
      - ./app:/app/app